---
deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - cd /home/nexaprow/repositories/laravel-backend
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan migrate --force
